# Generated by Django 4.0.6 on 2022-07-31 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('date_of_event', models.DateField(default=datetime.date.today, verbose_name='Дата события')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('datetime_of_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('categories', models.ManyToManyField(related_name='category', to='bloggy_app.category')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='EventPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='event_photos/', verbose_name='Фото')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloggy_app.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
