# Generated by Django 4.0.6 on 2022-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='bloggy_app.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to='static/posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='eventphotos',
            name='photo',
            field=models.ImageField(upload_to='static/event_photos/', verbose_name='Фото'),
        ),
    ]
